
export const READ_AUTH_TOKEN_PENDING = 'READ_AUTH_TOKEN_PENDING'
export const READ_AUTH_TOKEN_SUCCESS = 'READ_AUTH_TOKEN_SUCCESS'
export const READ_AUTH_TOKEN_FAILURE = 'READ_AUTH_TOKEN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const EXTEND_FILE_LIST = 'EXTEND_FILE_LIST'
export const DELETE_FOLDER_RECURSIVELY = 'DELETE_FOLDER_RECURSIVELY'
