
export const READ_AUTH_TOKEN_PENDING = 'READ_AUTH_TOKEN_PENDING'
export const READ_AUTH_TOKEN_SUCCESS = 'READ_AUTH_TOKEN_SUCCESS'
export const READ_AUTH_TOKEN_FAILURE = 'READ_AUTH_TOKEN_FAILURE'
export const LOGOUT = 'LOGOUT'
